"""What a writer may use, what it must declare, and what a reader gets back.

A paper writer is the worker with the most opportunity to do quiet damage.
Everything else in this system produces a diff a reviewer reads or a proposal a
human approves; a manuscript is prose, and prose can strengthen a claim, drop a
contrary result, or acquire a citation without any of it being visible as a
change to anything structured.

So the writer is bounded on both sides. On the way in, it receives a
:class:`SourcePacket` -- accepted Claims with the human approval that stands
behind each one, the Evidence those Claims rest on, the Experiments that
Evidence reaches, selected literature, and the limitations nobody has resolved.
Never the raw literature text, and never an unaccepted Claim.

On the way out it must produce a :class:`SourceManifest` alongside the prose:
every Claim, Evidence, Experiment, and work it used. That manifest is checked
against the packet, and the prose is checked against the manifest. A citation
that appears in the text and in neither is the thing this design exists to
catch.
"""

from __future__ import annotations

import re
from enum import StrEnum
from typing import Self

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from research_os.automation.models import safe_relative_path, utc_now
from research_os.models import NonBlankStr

DRAFT_ID_RE = re.compile(r"^DRAFT-[0-9]{8}T[0-9]{6}Z-[0-9a-f]{8}$")


class SectionKind(StrEnum):
    """What part of a manuscript a writing task is for.

    Named rather than free text because the instructions differ meaningfully.
    A results section may state numbers; a discussion may not introduce them. A
    limitations section is the one place the writer is asked to be *more*
    negative than its sources rather than less.
    """

    ABSTRACT = "abstract"
    INTRODUCTION = "introduction"
    METHODS = "methods"
    RESULTS = "results"
    DISCUSSION = "discussion"
    LIMITATIONS = "limitations"
    RELATED_WORK = "related_work"
    CONCLUSION = "conclusion"
    OTHER = "other"


class ClaimEntry(BaseModel):
    """One accepted Claim, with the human approval that stands behind it.

    ``approval_review_id`` is not decoration. R0 lets a Claim be accepted only
    with a concluded human approve Review bound to its current digest and to
    every piece of Evidence and every Experiment it reaches. Carrying that
    review's id into the packet means the writer -- and the human reading the
    manifest afterwards -- can see *which* approval a sentence rests on.
    """

    model_config = ConfigDict(extra="forbid")

    claim_id: NonBlankStr
    title: NonBlankStr
    statement: NonBlankStr
    digest: str
    approval_review_id: NonBlankStr
    approved_findings: str = ""
    supporting_evidence: list[str] = Field(default_factory=list)
    contrary_evidence: list[str] = Field(default_factory=list)
    contrary_evidence_addressed: str | None = None
    hypotheses: list[str] = Field(default_factory=list)


class EvidenceEntry(BaseModel):
    """One Evidence object a supplied Claim rests on."""

    model_config = ConfigDict(extra="forbid")

    evidence_id: NonBlankStr
    title: NonBlankStr
    statement: NonBlankStr
    kind: NonBlankStr
    status: NonBlankStr
    digest: str
    experiment_id: str | None = None
    citation: str | None = None
    notes: str | None = None
    contrary: bool = False
    """Whether this contradicts the Claim that references it.

    Carried explicitly so a writer cannot silently omit it and a reviewer can
    check it was addressed. Dropping contrary evidence is the single most
    damaging thing a writer could do here, and it is invisible unless the packet
    names it as contrary.
    """


class ExperimentEntry(BaseModel):
    """One Experiment whose provenance a supplied Evidence reaches."""

    model_config = ConfigDict(extra="forbid")

    experiment_id: NonBlankStr
    title: NonBlankStr
    purpose: NonBlankStr
    status: NonBlankStr
    digest: str
    primary_metrics: list[str] = Field(default_factory=list)
    decision_rule: str | None = None
    predictions: list[str] = Field(default_factory=list)
    provenance: dict[str, str] = Field(default_factory=dict)
    result_manifest: str | None = None
    artifacts: list[str] = Field(default_factory=list)


class LiteratureEntry(BaseModel):
    """One retrieved work a writer may cite, and the key it must cite it by."""

    model_config = ConfigDict(extra="forbid")

    work_key: NonBlankStr
    citation_key: NonBlankStr
    """The token the writer must use in the prose.

    A single deterministic key per work, generated by the packet builder, so
    checking a citation is exact-match rather than fuzzy name-and-year
    comparison. A key that does not appear in the packet is a fabricated
    citation, and the check that finds it is a set difference.
    """

    title: str = ""
    authors: list[str] = Field(default_factory=list)
    year: int | None = None
    venue: str | None = None
    doi: str | None = None
    is_retracted: bool = False
    retraction_note: str | None = None


class SourcePacket(BaseModel):
    """Everything a writer may use, and nothing else.

    Assembled deterministically from the capsule and the literature index. The
    writer never receives raw paper text: it receives these structured entries,
    whose literature half has already passed the citation check in the
    literature analyst.
    """

    model_config = ConfigDict(extra="forbid")

    schema_version: int = 1
    project_id: NonBlankStr
    project_path: str
    base_commit: str | None = None
    generated_at: str = Field(default_factory=utc_now)
    claims: list[ClaimEntry] = Field(default_factory=list)
    evidence: list[EvidenceEntry] = Field(default_factory=list)
    experiments: list[ExperimentEntry] = Field(default_factory=list)
    literature: list[LiteratureEntry] = Field(default_factory=list)
    limitations: list[NonBlankStr] = Field(default_factory=list)
    excluded_claims: dict[str, str] = Field(default_factory=dict)
    """Claims that were asked for but withheld, and why.

    Reported rather than dropped. A writer that silently did not receive a Claim
    would write around a hole; a human who asked for it deserves to be told it
    is not accepted, or its approval is stale, and which.
    """

    @property
    def claim_ids(self) -> frozenset[str]:
        return frozenset(item.claim_id for item in self.claims)

    @property
    def evidence_ids(self) -> frozenset[str]:
        return frozenset(item.evidence_id for item in self.evidence)

    @property
    def experiment_ids(self) -> frozenset[str]:
        return frozenset(item.experiment_id for item in self.experiments)

    @property
    def citation_keys(self) -> frozenset[str]:
        return frozenset(item.citation_key for item in self.literature)

    @property
    def contrary_evidence(self) -> list[EvidenceEntry]:
        return [item for item in self.evidence if item.contrary]

    def numeric_vocabulary(self) -> frozenset[str]:
        """Return every number that appears anywhere in the supplied sources.

        What the draft's numbers are checked against. A figure in a manuscript
        that appears in no Claim, no Evidence, no Experiment, and no supplied
        work either came from the writer's own arithmetic or from nowhere, and
        both deserve a human's attention.
        """

        text = " ".join(
            [
                *(f"{item.title} {item.statement}" for item in self.claims),
                *(
                    f"{item.title} {item.statement} {item.notes or ''}"
                    for item in self.evidence
                ),
                *(
                    " ".join(
                        [
                            item.title,
                            item.purpose,
                            item.decision_rule or "",
                            " ".join(item.primary_metrics),
                            " ".join(item.predictions),
                        ]
                    )
                    for item in self.experiments
                ),
                *(f"{item.title} {item.year or ''}" for item in self.literature),
                *self.limitations,
            ]
        )
        return frozenset(NUMBER_RE.findall(text))


#: A number as it appears in prose. Used on both sides of the numeric check, so
#: "0.10" and "0.1" are compared as the strings they are rather than as floats:
#: a manuscript that rounds a result differently from its source has changed it.
NUMBER_RE = re.compile(r"(?<![A-Za-z0-9_.-])\d+(?:\.\d+)?(?![A-Za-z0-9_.])")


class SourceManifest(BaseModel):
    """What a writer says it used. Provenance, not prose.

    Required output alongside the draft, and validated against the packet: a
    manifest entry that was not supplied is refused outright. This is what makes
    the prose checkable, because the prose is then checked against the manifest
    rather than against a model's memory.
    """

    model_config = ConfigDict(extra="forbid")

    schema_version: int = 1
    draft_id: str
    section: SectionKind
    claim_ids: list[str] = Field(default_factory=list)
    evidence_ids: list[str] = Field(default_factory=list)
    experiment_ids: list[str] = Field(default_factory=list)
    citation_keys: list[str] = Field(default_factory=list)
    unresolved_caveats: list[NonBlankStr] = Field(default_factory=list)
    written_paths: list[str] = Field(default_factory=list)
    generated_at: str = Field(default_factory=utc_now)

    @field_validator("written_paths")
    @classmethod
    def _paths_are_repository_relative(cls, value: list[str]) -> list[str]:
        return [safe_relative_path(item) for item in value]

    @field_validator("draft_id")
    @classmethod
    def _draft_id_shape(cls, value: str) -> str:
        if DRAFT_ID_RE.fullmatch(value) is None:
            raise ValueError("draft_id must look like DRAFT-20260912T101500Z-0a1b2c3d")
        return value


class GroundingIssue(BaseModel):
    """One thing the deterministic checks found in a draft.

    Severity is set by the check rather than by a model. ``blocker`` means the
    draft asserts something its sources do not contain, which is the one class
    of problem a human must not have to find by reading.
    """

    model_config = ConfigDict(extra="forbid")

    check: NonBlankStr
    severity: NonBlankStr
    message: NonBlankStr
    detail: str = ""

    @property
    def blocking(self) -> bool:
        return self.severity.strip().lower() == "blocker"


class GroundingReport(BaseModel):
    """Everything the deterministic checks established about one draft."""

    model_config = ConfigDict(extra="forbid")

    draft_id: str
    issues: list[GroundingIssue] = Field(default_factory=list)
    checked_paths: list[str] = Field(default_factory=list)
    cited_keys: list[str] = Field(default_factory=list)
    referenced_object_ids: list[str] = Field(default_factory=list)
    unsupported_numbers: list[str] = Field(default_factory=list)

    @property
    def grounded(self) -> bool:
        return not any(item.blocking for item in self.issues)

    @property
    def blockers(self) -> list[GroundingIssue]:
        return [item for item in self.issues if item.blocking]


class WritingVerdict(StrEnum):
    """The verdicts a read-only writing review may return.

    The same three words the code reviewer uses, and for the same reason: this
    judges a draft, not science, and must never be mistakable for a human
    scientific Review.
    """

    PASS = "PASS"
    PASS_WITH_REPAIR = "PASS_WITH_REPAIR"
    FAIL = "FAIL"


class WritingFinding(BaseModel):
    """One reviewer finding about a draft. Advisory."""

    model_config = ConfigDict(extra="forbid")

    severity: NonBlankStr
    message: NonBlankStr
    path: str | None = None

    @field_validator("path")
    @classmethod
    def _repository_relative(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return safe_relative_path(value)


class WritingReview(BaseModel):
    """A read-only reviewer's structured judgement of one draft."""

    model_config = ConfigDict(extra="forbid")

    draft_id: str
    verdict: WritingVerdict
    summary: NonBlankStr
    findings: list[WritingFinding] = Field(default_factory=list)
    provider: NonBlankStr
    model: str | None = None
    independence: str = "unknown"
    independence_note: str = ""
    invocation_id: str | None = None
    raw_output_path: str | None = None


class DraftRecord(BaseModel):
    """The complete runtime record of one writing task."""

    model_config = ConfigDict(extra="forbid")

    schema_version: int = 1
    draft_id: str
    project_id: NonBlankStr
    project_path: str
    base_commit: str | None = None
    section: SectionKind
    instruction: NonBlankStr
    allowed_paths: list[str] = Field(default_factory=list)
    worktree_path: str | None = None
    branch: str | None = None
    created_at: str = Field(default_factory=utc_now)
    finished_at: str | None = None
    changed_paths: list[str] = Field(default_factory=list)
    diff_path: str | None = None
    manifest: SourceManifest | None = None
    grounding: GroundingReport | None = None
    review: WritingReview | None = None
    repair_attempts: int = Field(default=0, ge=0)
    repair_reason: str | None = None
    failure_reason: str | None = None
    provider: str = ""
    model: str | None = None
    invocation_ids: list[str] = Field(default_factory=list)

    @field_validator("draft_id")
    @classmethod
    def _draft_id_shape(cls, value: str) -> str:
        if DRAFT_ID_RE.fullmatch(value) is None:
            raise ValueError("draft_id must look like DRAFT-20260912T101500Z-0a1b2c3d")
        return value

    @field_validator("allowed_paths")
    @classmethod
    def _scope_paths(cls, value: list[str]) -> list[str]:
        return [safe_relative_path(item) for item in value]

    @model_validator(mode="after")
    def _no_capsule_writing(self) -> Self:
        """Refuse a writing scope that reaches a project's scientific files.

        A manuscript is prose about science. A writer that could edit
        ``.research/`` could change the science the prose is supposed to be
        about, which is the one thing no automated worker may do.
        """

        for entry in self.allowed_paths:
            normalised = entry.rstrip("/")
            if normalised == ".research" or normalised.startswith(".research/"):
                raise ValueError(
                    "a writing task may not be scoped to .research/; a paper "
                    "writer writes prose about the science, never the science"
                )
        return self

    @property
    def ready_for_human(self) -> bool:
        """Whether this draft is in a state a human should be shown.

        Deliberately strict. A draft whose citations do not resolve, or which
        asserts numbers its sources do not contain, is not something to hand
        over with a summary: the whole point of the checks is that a person
        should not have to find those by reading.
        """

        return (
            self.grounding is not None
            and self.grounding.grounded
            and self.review is not None
            and self.review.verdict is not WritingVerdict.FAIL
            and not self.failure_reason
        )
