-- One parent run, at most one successor. Enforced by the database.
--
-- `RuntimeStore.lock_run` was written to serialise this, and its docstring
-- described the race it was closing: two passes over the same parked objective
-- each see no successor and each open one. An adversarial review read the
-- implementation and found the lock does not close it. `pg_advisory_xact_lock`
-- is transaction-scoped, `lock_run` takes it inside its own `tx()`, and that
-- transaction commits before the function returns -- so the lock is already
-- released when `has_successor` runs, and long gone by the time `start_cycle`
-- inserts the row. The mutual exclusion was between the lock and nothing.
--
-- The lock could have been widened to span all three steps, but `start_cycle`
-- is a whole bounded cycle: it runs a LangGraph graph, makes model calls, and
-- takes minutes. Holding a database transaction open across it to protect one
-- `insert` is the wrong shape, and a lock held for minutes is a lock that
-- times out or gets abandoned.
--
-- So the invariant goes where invariants belong. A partial unique index says
-- "at most one row may name this parent", which is exactly the property
-- `has_successor` was checking for. The check stays as a cheap way to avoid
-- doing the work, and it is no longer what makes the outcome correct: the
-- second inserter now loses at the `insert`, whenever it arrives, with no
-- window at all.
--
-- Partial, because `parent_run_id is null` for every run a researcher starts
-- and those must not be unique with respect to each other.
create unique index if not exists research_runs_one_successor_idx
    on research_runs(parent_run_id) where parent_run_id is not null;
